name: CullingGames
version: '1.0-SNAPSHOT'
main: cronozx.cullinggames.CullingGames
api-version: '1.21'
authors: [ cronozx ]
softdepend: [CrazyEnvoys, EcoBits, EcoShop, EcoPets]

commands:
  queue:
    description: Joins queue
    usage: /queue
  reload:
    description: Reloads config
    usage: /reload
  forceStart:
    description: Force starts event
    usage: /forceStart
  forceStop:
    description: Force stops culling games
    usage: /forceStop
